---
openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
paths:
  /login:
    post:
      summary: Login
      operationId: login_login_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginCredentialsRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /register:
    post:
      summary: Register
      operationId: register_register_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /whoami:
    get:
      summary: Whoami
      operationId: whoami_whoami_get
      parameters:
        - description: Bearer token that contains the access token. Must be in 'Bearer ...' format
          required: false
          schema:
            title: Authentication
            description: Bearer token that contains the access token. Must be in 'Bearer ...' format
          name: authentication
          in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WhoAmIResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
components:
  schemas:
    LoginCredentialsRequest:
      title: LoginCredentialsRequest
      required:
        - username
        - password
      type: object
      properties:
        username:
          title: Username
          type: string
        password:
          title: Password
          type: string
    LoginResponse:
      title: LoginResponse
      required:
        - success
        - access_token
        - refresh_token
      type: object
      properties:
        success:
          title: Success
          type: boolean
        access_token:
          title: Access Token
          type: string
        refresh_token:
          title: Refresh Token
          type: string
    MessageResponse:
      title: MessageResponse
      required:
        - success
        - message
      type: object
      properties:
        success:
          title: Success
          type: boolean
        message:
          title: Message
          type: string
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
        - username
        - password
        - password2
      type: object
      properties:
        username:
          title: Username
          type: string
        password:
          title: Password
          type: string
        password2:
          title: Password2
          type: string
    WhoAmIResponse:
      title: WhoAmIResponse
      required:
        - success
        - username
      type: object
      properties:
        success:
          title: Success
          type: boolean
        username:
          title: Username
          type: string
